### PR TITLE
Now generates world when world doesn't exist

### PR DESCRIPTION
**Pull request by Gallion**
MLG now properly generates a world when it does not exist. I moved all of WorldVerify to Setup, since I felt it was a more proper name for what it did. Setup takes care of making sure the world exists, of restoring the level.dat backup if it exists and of creating the world if it does not exist.

### CODE REVIEW

**Comment by Morlok8k** [comment]
ok, i will review this change.

**Comment by Gallion** [comment]
Erm.. I'm not sure why :
bin/MLG-BuildID
bin/MinecraftLandGenerator.conf
have been deleted. Do you want me to fix my pull request?

**Comment by Morlok8k** [comment]
you can if you want.  i can fix it though.

**Comment by Gallion** [comment]
There, it should be better now.

**Pull request merged**
