### PR TITLE
Major design changes

### LINKED ISSUE #13: Major design changes
I'd like to implement a few changes to make this little project a more mature tool and easier to use. Things that could be improved IMO:

- [ ] Use Maven for dependency management
- [ ] Make it usable as library
- [ ] Proper logging system
- [ ] Proper CLI argument parsing using library
- [ ] Make use of Java name conventions
- [ ] Change license to a more accepted public domain license (like Unlicense or CC0)
- [ ] Make use of the GitHub release system for distributing the software

What do you think?

### PR DESCRIPTION
**Pull request by piegamesde**
Fixes #13. Non-exhaustive list of changes:

- Replaced all the `println`s with proper logging
- Replaced the command line with a new interface using a library (and also with a completely new design)
- Dependency handling is now done through Maven
- May not work with older versions of the Minecraft server anymore
- Removed all of the bloat and unused stuff (update and download feature, time measurement etc.)
- Simplified the server launch sequence (it is mostly the "alternate" one)
- Made it more library-friendly
- Added new generation mechanic using permanently loaded chunks (way faster)
- Added JavaDocs and one unit test

### CODE REVIEW

**Comment by VADemon** [comment]
> May not work with older versions of the Minecraft server anymore

Would be nice to keep it backwards-compatible, we are currently looking for an infdev/alpha pregenerator, this is the only accessible option.

(the other one is to rip out the chunk gen code)

**Comment by buchwasa** [comment]
Been unable to get this to work. Is this still a work in progress?

**Comment by piegamesde** [comment]
No, it's pretty much done feature-wise and I even use this to generate test world for another project. I just noticed that none of the documentation has been updated since all the changes were made. I'll do this soon™.

On the other hand: what have you tried and why didn't it work?

-----

**Edit**: I just noticed some commits with bug fixes on the `develop` branch I forgot to merge, this may be the reason.

**Comment by buchwasa** [comment]
@piegamesde I just tried running it and I get a getCallerClass error and shuts off right after. 

Edit: Probably would help if I was compiling on Java 8 haha
Edit Edit: Compiling on Java 11 gives me the warning, and shuts off, compiling on Java 8 gives me nothing and shuts off.

**Comment by piegamesde** [comment]
Since it seems that there are no plans to integrate our changes, we decided to continue the fork on our own: https://github.com/sommerlilie/MinecraftLandGenerator

@Wumpotamus Please create an issue there if it still doesn't work for you.

**Pull request closed without merging**
